import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Heart, Instagram, MessageCircle, ArrowRight, Phone, Sparkles, BookOpen, Users, Calendar, Menu, X, Play, Star, Compass, Target, Eye, BookMarked, UserPlus, Receipt, Mail } from "lucide-react";
import logoAsset from "@/assets/book-team-logo.png.asset.json";
import capaMantenha from "@/assets/mantenha.jpg.asset.json";
import capaCultura from "@/assets/cultura.jpg.asset.json";
import capaAtive from "@/assets/ative.jpg.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Book Team — Amor & Honra | Trilhas de leitura cristã" },
    { name: "description", content: "Ministério Book Team: trilhas de leitura, encontros presenciais e uma comunidade que vive amor e honra todos os dias." },
    { property: "og:title", content: "Book Team — Amor & Honra" },
    { property: "og:description", content: "Trilhas de leitura, encontros presenciais e uma comunidade cristã que vive amor e honra." },
  ] }),
  component: LandingPage,
});

function LandingPage() {
  return <div className="min-h-screen bg-background text-foreground"><Header /><HeroQuemSomos /><HowItWorks /><JornadaLivros /><EventosEspeciais /><Testimonials /><FaqSection /><Footer /></div>;
}

function Header() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 40); fn(); window.addEventListener("scroll", fn, { passive: true }); return () => window.removeEventListener("scroll", fn); }, []);
  const items = [
    ["#quem-somos", "Quem somos"], ["#cronograma", "Livros"], ["#eventos", "Encontros"],
  ];
  return <header className={`fixed top-0 z-50 w-full transition-all duration-500 ${scrolled ? "border-b border-border/60 bg-background/85 backdrop-blur-xl" : "bg-transparent"}`}>
    <div className="mx-auto flex h-16 max-w-7xl items-center justify-between gap-4 px-4 md:px-8">
      <Link to="/" className="flex items-center gap-2.5"><img src={logoAsset.url} alt="Book Team" className="h-9 w-9 rounded-full ring-1 ring-gold/40"/><div><p className="font-serif text-[15px] font-semibold tracking-wide">BOOK TEAM</p><p className="text-[10px] uppercase tracking-[0.2em] text-gold">amor & honra</p></div></Link>
      <nav className="hidden items-center gap-6 lg:flex">{items.map(([href,label]) => <a key={href} href={href} className="group relative text-[15px] font-medium text-foreground/80 hover:text-foreground">{label}<span className="absolute -bottom-1 left-0 h-0.5 w-0 bg-gold transition-all group-hover:w-full"/></a>)}<Link to="/inicio" className="text-[15px] font-medium text-foreground/80 hover:text-foreground">Área do aluno</Link><Link to="/admin" className="text-[15px] font-medium text-foreground/80 hover:text-foreground">Área administrativa</Link></nav>
      <div className="flex items-center gap-2"><Button asChild variant="ghost" size="sm" className="hidden sm:inline-flex"><Link to="/auth">Entrar</Link></Button><Button asChild size="sm" className="hidden bg-gold text-primary-foreground hover:bg-gold/90 sm:inline-flex"><Link to="/auth" search={{ mode: "signup" }}>Quero participar</Link></Button><button className="inline-flex h-10 w-10 items-center justify-center rounded-full lg:hidden" onClick={() => setOpen(v => !v)} aria-label="Menu">{open ? <X/> : <Menu/>}</button></div>
    </div>
    {open && <div className="border-t border-border/60 bg-background/95 lg:hidden"><div className="flex flex-col gap-1 p-4">{items.map(([href,label])=><a key={href} href={href} onClick={()=>setOpen(false)} className="rounded-lg px-3 py-3">{label}</a>)}<Link to="/inicio" className="rounded-lg px-3 py-3">Área do aluno</Link><Link to="/admin" className="rounded-lg px-3 py-3">Área administrativa</Link><div className="mt-2 flex gap-2 border-t pt-3"><Button asChild variant="outline" className="flex-1"><Link to="/auth">Entrar</Link></Button><Button asChild className="flex-1 bg-gold text-primary-foreground"><Link to="/auth" search={{mode:"signup"}}>Participar</Link></Button></div></div></div>}
  </header>;
}

function HeroQuemSomos() {
  const pilares = [
    [Eye, "Visão", "Todas as pessoas precisam conhecer o amor de Deus, independente da placa de igreja ou título pessoal."],
    [Target, "Missão", "Mostrar a possibilidade de viver o amor de Deus na sua plenitude, sendo cada um seu Perfeito Eu."],
    [Compass, "Objetivo", "Ajudar homens e mulheres a encontrar sua real identidade em Cristo."],
  ];
  return <section id="quem-somos" className="relative overflow-hidden pt-24"><div className="pointer-events-none absolute left-1/2 top-[38vh] h-[680px] w-[680px] -translate-x-1/2 -translate-y-1/2 rounded-full opacity-60 blur-3xl" style={{background:"radial-gradient(circle, oklch(0.45 0.13 25 / 0.55) 0%, transparent 65%)"}}/><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-4 pb-14 md:grid-cols-2 md:px-8 md:pt-12"><div className="flex justify-center md:justify-start"><img src={logoAsset.url} alt="Book Team — Amor & Honra" className="h-56 w-56 rounded-full shadow-2xl ring-1 ring-gold/40 md:h-80 md:w-80 lg:h-[22rem] lg:w-[22rem]"/></div><div className="flex flex-col items-center text-center md:items-start md:text-left"><span className="inline-flex items-center gap-2 rounded-full border border-gold/30 px-3.5 py-1.5 text-[11px] uppercase tracking-[0.18em] text-gold"><Sparkles className="h-3 w-3"/> Ministério Book Team</span><h1 className="mt-5 font-serif text-2xl font-semibold leading-[1.15] md:text-3xl lg:text-4xl">O Ministério Book Team estuda livros cristãos que ensinam Homens e Mulheres a viver uma cultura de <span className="text-gradient-gold italic">amor & honra</span>!</h1><p className="mt-5 max-w-xl text-base leading-relaxed text-foreground/75 md:text-[17px]">Trilhas de leitura cristã, encontros presenciais e uma comunidade que transforma livros em conversas — e conversas em jornada.</p><div className="mt-7 flex flex-wrap justify-center gap-3 md:justify-start"><Button asChild size="lg" className="bg-gold text-primary-foreground shadow-glow-gold hover:bg-gold/90"><a href="#como-funciona">Quero participar <ArrowRight className="ml-2 h-4 w-4"/></a></Button><Button asChild size="lg" variant="outline"><a href="#cronograma"><Play className="mr-2 h-4 w-4"/>Conheça os livros</a></Button></div></div></div><div className="relative mx-auto max-w-7xl px-4 pb-16 md:px-8"><div className="text-center"><span className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Quem somos</span></div><div className="mt-10 grid gap-4 sm:grid-cols-3">{pilares.map(([Icon,title,text])=><div key={title as string} className="rounded-2xl border border-border/60 bg-card/60 p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gold/10 text-gold"><Icon className="h-5 w-5"/></div><p className="mt-4 font-serif text-lg font-semibold">{title as string}</p><p className="mt-1.5 text-[13px] leading-relaxed text-foreground/70">{text as string}</p></div>)}</div></div></section>;
}

function HowItWorks(){const steps=[[BookMarked,"Inicie pelo livro 1","Toda jornada começa no primeiro livro da trilha — a ordem preserva o sentido da leitura."],[UserPlus,"Faça sua inscrição","Preencha seus dados e reserve sua vaga no próximo encontro presencial."],[Receipt,"Pague e envie o comprovante","Faça o PIX e anexe o comprovante direto no seu painel — é rápido e seguro."],[Mail,"Aguarde a confirmação","Você receberá no seu e-mail a confirmação e todos os dados da inscrição."]];return <section id="como-funciona" className="border-t border-border/40 py-14"><div className="mx-auto max-w-7xl px-4 md:px-8"><span className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Como funciona</span><ol className="mt-10 grid gap-8 md:grid-cols-4">{steps.map(([Icon,title,desc],i)=><li key={title as string} className="relative text-center"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-gold/50 bg-background shadow-glow-gold"><img src={logoAsset.url} alt="Book Team" className="h-14 w-14 rounded-full"/><span className="absolute ml-14 mt-14 flex h-6 w-6 items-center justify-center rounded-full border border-gold/50 bg-background text-[11px] font-bold text-gold">{i+1}</span></div><div className="mt-6 rounded-2xl border border-border/60 bg-card/70 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-gold">Passo {i+1}</p><p className="mt-1 font-serif text-lg font-semibold">{title as string}</p><p className="mt-1.5 text-[13px] leading-relaxed text-foreground/70">{desc as string}</p></div></li>)}</ol></div></section>}

function JornadaLivros(){const livros=[
 [1,"Mantenha Seu Amor Aceso","",capaMantenha.url],[2,"Cultura da Honra","",capaCultura.url],[3,"Livro 3","",null],[4,"Livro 4","",null],[5,"Organize a Sua Desordem Mental","",null],[6,"O Despertar da Leoa","",null],[7,"Livro 7","",null],[8,"Os Caminhos Sobrenaturais da Realeza","",null],[9,"O Poder Sobrenatural de uma Mente Transformada","",null],[10,"Impunível","Danny Silk",capaAtive.url]];return <section id="cronograma" className="border-t border-border/40 bg-gradient-to-b from-background via-card/30 to-background py-16"><div className="mx-auto max-w-7xl px-4 md:px-8"><h2 className="font-serif text-2xl font-semibold md:text-3xl">Uma jornada em livros</h2><p className="mt-4 max-w-2xl text-[15px] leading-relaxed text-foreground/70">Cada trilha segue uma ordem — para começar o próximo livro, é preciso concluir o anterior. Seu histórico registra todo o caminho percorrido.</p><div className="scrollbar-hidden mt-8 flex gap-4 overflow-x-auto pb-4 md:gap-8">{livros.map(([n,title,author,img])=><Link key={n as number} to="/livros/$id" params={{id:`placeholder-${n}`}} className="group relative w-[58vw] max-w-[240px] shrink-0 overflow-hidden rounded-r-2xl rounded-l-md border border-gold/20 bg-gradient-to-br from-[oklch(0.4_0.12_25)] to-[oklch(0.2_0.05_20)] shadow-book"><div className="aspect-[2/3]">{img?<img src={img as string} alt={title as string} className="h-full w-full object-cover"/>:<div className="flex h-full flex-col items-center justify-center p-5 text-center"><BookOpen className="h-10 w-10 text-gold"/><p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.18em] text-gold">Capa em breve</p></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent"/><div className="absolute left-3 top-3 rounded-full border border-gold/30 bg-black/45 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.15em] text-gold">Livro {n as number}</div><div className="absolute inset-x-0 bottom-0 p-5"><p className="text-[10px] uppercase tracking-[0.2em] text-gold">Jornada</p><p className="mt-1 font-serif text-lg font-semibold italic leading-tight">{title as string}</p>{author?<p className="mt-1 text-xs text-foreground/75">{author as string}</p>:null}<div className="mt-3 flex items-center justify-between text-[11px] text-foreground/70"><span>Ver detalhes</span><ArrowRight className="h-4 w-4 text-gold"/></div></div></div></Link>)}</div></div></section>}

function EventosEspeciais(){return <section id="eventos" className="py-14"><div className="mx-auto max-w-7xl px-4 md:px-8"><div className="overflow-hidden rounded-3xl border border-gold/20 gradient-wine p-8 shadow-premium md:p-14"><div className="grid gap-10 md:grid-cols-[1.2fr_1fr] md:items-center"><div><span className="inline-flex items-center gap-2 rounded-full border border-gold/30 px-3 py-1.5 text-[10px] uppercase tracking-[0.2em] text-gold"><Sparkles className="h-3 w-3"/> Momentos para todos</span><h2 className="mt-4 font-serif text-3xl font-semibold md:text-4xl">Momentos aberto para todos</h2><p className="mt-4 max-w-lg text-[15px] leading-relaxed text-foreground/80">Além das trilhas dos livros, promovemos retiros, conferências e celebrações abertos ao público — um convite para viver a cultura de amor e honra.</p><Button asChild className="mt-7 bg-gold text-primary-foreground"><a href="#contato">Falar com a gente</a></Button></div><div className="grid grid-cols-2 gap-3">{[[Heart,"Open House"],[Users,"Bazar"],[Sparkles,"Café Colonial"],[Star,"Mulheres de Valor"],[Calendar,"Cantar"],[Users,"Encontro de Casais"]].map(([Icon,label])=><div key={label as string} className="flex aspect-square flex-col items-center justify-center gap-2 rounded-2xl border border-gold/20 bg-black/25"><Icon className="h-6 w-6 text-gold"/><p className="font-serif text-sm font-semibold">{label as string}</p></div>)}</div></div></div></div></section>}

function Testimonials(){const items=[["Voltei a ler no ritmo que sempre quis, com gente que topa conversar de verdade.","Marina R.","Curitiba - PR"],["Os encontros presenciais são o diferencial. Saio de cada um com ideias novas.","Bruno L.","São Paulo - SP"],["A cultura de honra mudou como eu conduzo meu casamento e meu trabalho.","Camila F.","Curitiba - PR"]];return <section className="border-t border-border/40 bg-gradient-to-b from-card/40 to-background py-14"><div className="mx-auto max-w-7xl px-4 md:px-8"><div className="text-center"><span className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Depoimentos</span><h2 className="mt-3 font-serif text-3xl font-semibold">Quem vive, conta</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{items.map(([q,name,city])=><blockquote key={name as string} className="rounded-3xl border border-border/60 bg-card p-8"><div className="flex gap-0.5">{[1,2,3,4,5].map(i=><Star key={i} className="h-4 w-4 fill-gold text-gold"/>)}</div><p className="mt-5 font-serif text-[17px] italic leading-relaxed">"{q as string}"</p><footer className="mt-6 border-t border-border/50 pt-5"><p className="text-sm font-semibold">{name as string}</p><p className="text-[11px] text-foreground/60">{city as string}</p></footer></blockquote>)}</div></div></section>}

function FaqSection(){const items=[["Preciso pagar mensalidade?","Não. Você paga apenas pelos encontros em que se inscrever, via PIX."],["Os encontros são online?","Não. Todos os encontros são presenciais. A cidade é indicada em cada evento."],["Como recebo o certificado?","Ao concluir uma trilha, o certificado é emitido pela administração e fica disponível na sua área."],["Posso escolher qualquer livro?","As leituras seguem a ordem da trilha escolhida — assim a comunidade caminha junta."]];return <section id="faq" className="border-t border-border/40 py-14"><div className="mx-auto max-w-3xl px-4 md:px-8"><div className="text-center"><span className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Perguntas frequentes</span><h2 className="mt-3 font-serif text-3xl font-semibold">Dúvidas comuns</h2></div><Accordion type="single" collapsible className="mt-8">{items.map(([q,a],i)=><AccordionItem key={i} value={`item-${i}`}><AccordionTrigger>{q as string}</AccordionTrigger><AccordionContent className="text-sm leading-relaxed text-foreground/70">{a as string}</AccordionContent></AccordionItem>)}</Accordion></div></section>}

function Footer(){return <footer id="contato" className="border-t border-border/60 bg-gradient-to-b from-background to-black/50 py-14"><div className="mx-auto max-w-7xl px-4 md:px-8"><div className="grid gap-10 md:grid-cols-4"><div className="md:col-span-1"><div className="flex items-center gap-3"><img src={logoAsset.url} alt="Book Team" className="h-10 w-10 rounded-full"/><div><p className="font-serif font-semibold">BOOK TEAM</p><p className="text-[10px] uppercase tracking-[0.2em] text-gold">amor & honra</p></div></div><p className="mt-5 text-sm leading-relaxed text-foreground/70">Um ministério cristão que transforma páginas em conversas — e conversas em jornada.</p><p className="mt-5 border-l-2 border-gold/40 pl-4 font-serif text-sm italic">"Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros."<br/><span className="text-xs text-foreground/50">Romanos 12:10</span></p></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Navegação</p><div className="mt-4 space-y-2 text-sm text-foreground/70"><a className="block hover:text-foreground" href="#quem-somos">Quem somos</a><a className="block hover:text-foreground" href="#cronograma">Livros</a><a className="block hover:text-foreground" href="#faq">FAQ</a></div></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Contato</p><div className="mt-4 space-y-3 text-sm text-foreground/70"><p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5 text-gold"/>41 3082-5553</p><a className="flex items-center gap-2 hover:text-foreground" href="https://wa.me/554130825553"><MessageCircle className="h-3.5 w-3.5 text-gold"/>WhatsApp</a><a className="flex items-center gap-2 hover:text-foreground" href="https://instagram.com/bookteamamor"><Instagram className="h-3.5 w-3.5 text-gold"/>@bookteamamor</a></div></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-gold">Comece agora</p><p className="mt-4 text-sm text-foreground/70">Crie sua conta e participe do próximo encontro.</p><Button asChild className="mt-4 w-full bg-gold text-primary-foreground"><Link to="/auth" search={{mode:"signup"}}>Criar minha conta</Link></Button></div></div><div className="mt-10 border-t border-border/40 pt-6 text-center text-[11px] text-foreground/50">© {new Date().getFullYear()} Ministério Book Team. Todos os direitos reservados. • Curitiba - PR</div></div></footer>}
