import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { Users, Search, ShieldCheck, UserRound, Loader2, UserPlus, FileSpreadsheet, Upload, Download, Trash2, UserX, UserCheck } from "lucide-react";
import * as XLSX from "xlsx";

export const Route = createFileRoute("/_admin/admin/participantes")({
  head: () => ({ meta: [{ title: "Alunos — Admin — Book Team" }, { name: "robots", content: "noindex" }] }),
  component: AdminParticipantes,
});

type Participante = { id:string; nome:string; email:string; telefone:string|null; cidade:string|null; estado:string|null; status:string; created_at:string };
type RoleRow = { user_id:string; role:"admin"|"participante" };
type Perfil = "aluno"|"adm"|"aluno_adm";
type Cadastro = { nome:string; email:string; cpf:string; telefone:string; cidade:string; estado:string; perfil:Perfil };
type ImportRow = Cadastro & { linha:number };
const vazio:Cadastro={nome:"",email:"",cpf:"",telefone:"",cidade:"",estado:"",perfil:"aluno"};
function norm(v:unknown){return String(v??"").trim()}
function key(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function col(row:Record<string,unknown>,aliases:string[]){const keys=new Set(aliases.map(key));const k=Object.keys(row).find(x=>keys.has(key(x)));return k?norm(row[k]):""}
function perfil(v:string):Perfil{const x=key(v);if(x.includes("alunoadm")||x.includes("ambos"))return"aluno_adm";if(x==="adm"||x.includes("administrador"))return"adm";return"aluno"}

function AdminParticipantes(){
 const qc=useQueryClient(); const [busca,setBusca]=useState(""); const [alterando,setAlterando]=useState<string|null>(null); const [modal,setModal]=useState<"manual"|"excel"|null>(null); const [form,setForm]=useState<Cadastro>(vazio); const [importadas,setImportadas]=useState<ImportRow[]>([]); const [arquivo,setArquivo]=useState(""); const inputExcel=useRef<HTMLInputElement>(null);
 const alunosQuery=useQuery({queryKey:["admin-alunos"],queryFn:async()=>{const {data,error}=await supabase.from("participantes").select("id,nome,email,telefone,cidade,estado,status,created_at").order("created_at",{ascending:false});if(error)throw error;return(data??[]) as Participante[]}});
 const rolesQuery=useQuery({queryKey:["admin-user-roles"],queryFn:async()=>{const {data,error}=await supabase.from("user_roles").select("user_id,role");if(error)throw error;return(data??[]) as RoleRow[]}});
 const admins=useMemo(()=>new Set((rolesQuery.data??[]).filter(r=>r.role==="admin").map(r=>r.user_id)),[rolesQuery.data]);
 const alunos=useMemo(()=>{const t=busca.trim().toLowerCase();return(alunosQuery.data??[]).filter(a=>!t||a.nome.toLowerCase().includes(t)||a.email.toLowerCase().includes(t)||(a.telefone??"").includes(t))},[alunosQuery.data,busca]);
 const criar=useMutation({mutationFn:async(rows:Cadastro[])=>{const {data,error}=await supabase.functions.invoke("bookteam-create-users",{body:{users:rows}});if(error)throw error;return data as {results:{email:string;ok:boolean;error?:string}[]}},onSuccess:async data=>{const ok=(data.results??[]).filter(r=>r.ok).length;const erros=(data.results??[]).filter(r=>!r.ok);toast.success(`${ok} cadastro(s) criado(s). Convite enviado por e-mail.`);if(erros.length)toast.error(`${erros.length} cadastro(s) não foram criados.`);await qc.invalidateQueries({queryKey:["admin-alunos"]});await qc.invalidateQueries({queryKey:["admin-user-roles"]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Não foi possível criar o cadastro.")});
 const gerenciar=useMutation({mutationFn:async(args:{participante_id:string;action:"ativar"|"inativar"|"excluir"})=>{const {data,error}=await supabase.functions.invoke("bookteam-manage-user",{body:args});if(error)throw error;if(!data?.ok)throw new Error(data?.error??"Não foi possível executar a ação.");return data},onSuccess:async(_,v)=>{toast.success(v.action==="excluir"?"Aluno excluído.":v.action==="inativar"?"Aluno inativado.":"Aluno ativado.");await qc.invalidateQueries({queryKey:["admin-alunos"]});await qc.invalidateQueries({queryKey:["admin-user-roles"]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Não foi possível executar a ação.")});
 async function salvarManual(){if(!form.nome.trim()||!form.email.trim()){toast.error("Nome e e-mail são obrigatórios.");return}if(!/^\S+@\S+\.\S+$/.test(form.email.trim())){toast.error("Informe um e-mail válido.");return}await criar.mutateAsync([form]);setForm(vazio);setModal(null)}
 async function lerExcel(file:File){setArquivo(file.name);try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:""});const rows:ImportRow[]=raw.map((r,i)=>({linha:i+2,nome:col(r,["nome","nome completo","aluno","aluna"]),email:col(r,["email","e-mail","e mail"]),cpf:col(r,["cpf"]),telefone:col(r,["telefone","celular","fone"]),cidade:col(r,["cidade"]),estado:col(r,["estado","uf"]),perfil:perfil(col(r,["perfil","perfil de acesso","tipo","acesso"]))})).filter(r=>r.nome&&r.email);setImportadas(rows);if(!rows.length)toast.error("Nenhum aluno válido encontrado no Excel.")}catch{toast.error("Não foi possível ler o Excel.")}}
 function modelo(){const ws=XLSX.utils.json_to_sheet([{Nome:"Maria da Silva",Email:"maria@email.com",CPF:"",Telefone:"",Cidade:"Curitiba",Estado:"PR",Perfil:"Aluno"}]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Alunos");XLSX.writeFile(wb,"modelo-alunos-book-team.xlsx")}
 async function importar(){if(!importadas.length){toast.error("Escolha um Excel com alunos.");return}await criar.mutateAsync(importadas.map(({linha,...r})=>r));setImportadas([]);setArquivo("");setModal(null)}
 async function adm(aluno:Participante,v:boolean){setAlterando(aluno.id);const {error}=v?await supabase.from("user_roles").upsert({user_id:aluno.id,role:"admin"},{onConflict:"user_id,role"}):await supabase.from("user_roles").delete().eq("user_id",aluno.id).eq("role","admin");if(error)toast.error(error.message.includes("admin")?"Não é possível remover o último ADM ou o próprio acesso.":error.message);else{toast.success(v?`${aluno.nome} agora é ADM.`:`Acesso ADM removido de ${aluno.nome}.`);await qc.invalidateQueries({queryKey:["admin-user-roles"]})}setAlterando(null)}
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-serif text-3xl font-bold">Alunos</h1><p className="text-muted-foreground">Cadastros, perfis, ativação e gerenciamento dos alunos.</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>{setForm(vazio);setModal("manual")}} className="gap-2"><UserPlus className="h-4 w-4"/>Cadastrar aluno</Button><Button variant="outline" onClick={()=>{setImportadas([]);setArquivo("");setModal("excel")}} className="gap-2"><FileSpreadsheet className="h-4 w-4"/>Importar Excel</Button><Badge variant="secondary" className="inline-flex items-center gap-1"><Users className="h-3 w-3"/>{alunos.length} aluno(s)</Badge></div></div>
  <Card><CardContent className="p-4"><Label>Buscar aluno</Label><div className="relative mt-1.5 max-w-xl"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground"/><Input placeholder="Nome, e-mail ou telefone" value={busca} onChange={e=>setBusca(e.target.value)} className="pl-8"/></div></CardContent></Card>
  <Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-sm"><thead className="border-b border-border text-left text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-4 py-3">Aluno</th><th className="px-4 py-3">Contato</th><th className="px-4 py-3">Cadastro</th><th className="px-4 py-3">Perfil</th><th className="px-4 py-3">Ações</th></tr></thead><tbody>{alunos.map(a=>{const isAdm=admins.has(a.id);const ativo=a.status.toLowerCase()!=="inativo";return <tr key={a.id} className="border-b border-border/60 last:border-0"><td className="px-4 py-4"><div className="font-medium">{a.nome}</div><div className="text-xs text-muted-foreground">Status: {a.status}</div></td><td className="px-4 py-4 text-muted-foreground"><div>{a.email}</div><div className="text-xs">{a.telefone??""}</div>{a.cidade&&<div className="text-xs">{a.cidade}/{a.estado??""}</div>}</td><td className="px-4 py-4 text-muted-foreground">{new Date(a.created_at).toLocaleDateString("pt-BR")}</td><td className="px-4 py-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary" className="gap-1"><UserRound className="h-3 w-3"/>Aluno</Badge><div className="flex items-center gap-2 rounded-lg border px-3 py-2"><ShieldCheck className="h-4 w-4 text-primary"/><span>ADM</span><Switch checked={isAdm} disabled={alterando===a.id} onCheckedChange={v=>adm(a,v)}/></div></div></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={gerenciar.isPending} onClick={()=>gerenciar.mutate({participante_id:a.id,action:ativo?"inativar":"ativar"})}>{ativo?<><UserX className="mr-1 h-4 w-4"/>Inativar</>:<><UserCheck className="mr-1 h-4 w-4"/>Ativar</>}</Button><Button size="sm" variant="destructive" disabled={gerenciar.isPending||isAdm} title={isAdm?"Remova o ADM antes de excluir":"Excluir aluno"} onClick={()=>{if(confirm(`Excluir definitivamente ${a.nome}?`))gerenciar.mutate({participante_id:a.id,action:"excluir"})}}><Trash2 className="mr-1 h-4 w-4"/>Excluir</Button></div></td></tr>})}</tbody></table>{alunosQuery.isLoading&&<p className="p-6 text-sm text-muted-foreground">Carregando alunos…</p>}{alunos.length===0&&!alunosQuery.isLoading&&<p className="p-6 text-sm text-muted-foreground">Nenhum aluno encontrado.</p>}</CardContent></Card>
  <div className="rounded-xl border border-dashed border-border bg-card/50 p-4 text-sm text-muted-foreground"><strong className="text-foreground">Cadastro manual:</strong> cria a conta, registra o aluno e envia convite por e-mail. O perfil pode ser Aluno, ADM ou Aluno + ADM. <strong className="text-foreground">Inativar</strong> preserva os dados; <strong className="text-foreground">Excluir</strong> é definitivo e será bloqueado se houver inscrição.</div>
  <Dialog open={modal==="manual"} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Cadastrar aluno</DialogTitle><DialogDescription>O aluno receberá um convite para definir a própria senha.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2">{([["nome","Nome completo"],["email","E-mail"],["cpf","CPF"],["telefone","Telefone"],["cidade","Cidade"],["estado","Estado / UF"]] as const).map(([k,l])=><div key={k} className="space-y-1.5"><Label>{l}</Label><Input type={k==="email"?"email":"text"} value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></div>)}<div className="space-y-1.5 sm:col-span-2"><Label>Perfil de acesso</Label><Select value={form.perfil} onValueChange={v=>setForm(f=>({...f,perfil:v as Perfil}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="aluno">Aluno</SelectItem><SelectItem value="adm">ADM</SelectItem><SelectItem value="aluno_adm">Aluno + ADM</SelectItem></SelectContent></Select></div></div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={()=>setModal(null)}>Cancelar</Button><Button onClick={salvarManual} disabled={criar.isPending}>{criar.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<UserPlus className="mr-2 h-4 w-4"/>}Cadastrar</Button></div></DialogContent></Dialog>
  <Dialog open={modal==="excel"} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Importar alunos por Excel</DialogTitle><DialogDescription>Colunas aceitas: Nome, Email, CPF, Telefone, Cidade, Estado e Perfil.</DialogDescription></DialogHeader><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={modelo} className="gap-2"><Download className="h-4 w-4"/>Baixar modelo</Button><Button onClick={()=>inputExcel.current?.click()} className="gap-2"><Upload className="h-4 w-4"/>Escolher Excel</Button><input ref={inputExcel} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>e.target.files?.[0]&&lerExcel(e.target.files[0])}/></div>{arquivo&&<p className="mt-3 text-sm text-muted-foreground">Arquivo: {arquivo}</p>}{importadas.length>0&&<div className="mt-4 max-h-72 overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="border-b"><tr><th className="p-2 text-left">Linha</th><th className="p-2 text-left">Nome</th><th className="p-2 text-left">E-mail</th><th className="p-2 text-left">Perfil</th></tr></thead><tbody>{importadas.map(r=><tr key={r.linha} className="border-b last:border-0"><td className="p-2">{r.linha}</td><td className="p-2">{r.nome}</td><td className="p-2">{r.email}</td><td className="p-2">{r.perfil}</td></tr>)}</tbody></table></div>}<div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>setModal(null)}>Cancelar</Button><Button onClick={importar} disabled={!importadas.length||criar.isPending}>{criar.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<FileSpreadsheet className="mr-2 h-4 w-4"/>}Criar {importadas.length||""} aluno(s)</Button></div></DialogContent></Dialog>
 </div>
}
