import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { MessageSquare, Send, CheckCheck } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/_admin/admin/mensagens")({ component: AdminMensagensPage });

type Msg = { id:string; participante_id:string; remetente_id:string; remetente_tipo:string; assunto:string|null; mensagem:string; lida:boolean; created_at:string; participantes?: { nome:string|null; email:string|null }|null };

function AdminMensagensPage(){
 const qc=useQueryClient(); const [resposta,setResposta]=useState(""); const [selecionada,setSelecionada]=useState<Msg|null>(null);
 const q=useQuery({queryKey:["admin-mensagens"],queryFn:async()=>{const {data,error}=await supabase.from("mensagens_admin").select("*, participantes(nome,email)").order("created_at",{ascending:false});if(error)throw error;return (data??[]) as Msg[]}});
 const responder=useMutation({mutationFn:async()=>{if(!selecionada||!resposta.trim())throw new Error("Digite uma resposta.");const {data:u}=await supabase.auth.getUser();if(!u.user)throw new Error("Sessão expirada.");const {error}=await supabase.from("mensagens_admin").insert({participante_id:selecionada.participante_id,remetente_id:u.user.id,remetente_tipo:"admin",assunto:selecionada.assunto||"Mensagem do Book Team",mensagem:resposta.trim()});if(error)throw error;await supabase.from("mensagens_admin").update({lida:true}).eq("id",selecionada.id)},onSuccess:()=>{toast.success("Resposta enviada.");setResposta("");setSelecionada(null);qc.invalidateQueries({queryKey:["admin-mensagens"]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Não foi possível enviar.")});
 const marcar=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("mensagens_admin").update({lida:true}).eq("id",id);if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:["admin-mensagens"]})});
 const mensagens=q.data??[];
 return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Comunicação</p><h1 className="font-serif text-2xl font-semibold sm:text-3xl">Mensagens dos alunos</h1><p className="mt-1 text-sm text-muted-foreground">Receba dúvidas dos alunos e responda pelo próprio Book Team.</p></div><div className="grid gap-4 lg:grid-cols-[1fr_420px]"><Card><CardHeader><CardTitle className="text-lg">Caixa de entrada</CardTitle></CardHeader><CardContent className="space-y-2">{q.isLoading&&<p className="text-sm text-muted-foreground">Carregando…</p>}{!q.isLoading&&mensagens.length===0&&<p className="text-sm text-muted-foreground">Nenhuma mensagem ainda.</p>}{mensagens.map(m=><button key={m.id} type="button" className={`w-full rounded-lg border p-3 text-left transition-colors hover:bg-secondary/50 ${!m.lida?"border-primary/50 bg-primary/5":""}`} onClick={()=>{setSelecionada(m);if(!m.lida)marcar.mutate(m.id)}}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-medium">{m.participantes?.nome||m.participantes?.email||"Aluno"}</p><p className="text-xs text-muted-foreground">{m.assunto||"Sem assunto"} · {new Date(m.created_at).toLocaleString("pt-BR")}</p></div>{!m.lida&&<Badge>Nova</Badge>}</div><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{m.mensagem}</p></button>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-lg">{selecionada?"Responder aluno":"Selecione uma mensagem"}</CardTitle></CardHeader><CardContent className="space-y-3">{selecionada?<><div className="rounded-lg bg-muted p-3"><p className="text-xs font-medium text-muted-foreground">{selecionada.participantes?.nome||selecionada.participantes?.email||"Aluno"}</p><p className="mt-1 text-sm whitespace-pre-wrap">{selecionada.mensagem}</p></div><Textarea rows={6} value={resposta} onChange={e=>setResposta(e.target.value)} placeholder="Digite sua resposta…"/><div className="flex gap-2"><Button disabled={responder.isPending} onClick={()=>responder.mutate()}><Send className="mr-2 h-4 w-4"/>Enviar resposta</Button><Button variant="outline" onClick={()=>setSelecionada(null)}><CheckCheck className="mr-2 h-4 w-4"/>Fechar</Button></div></>:<div className="flex min-h-48 flex-col items-center justify-center text-center text-sm text-muted-foreground"><MessageSquare className="mb-2 h-8 w-8"/><p>Escolha uma mensagem para visualizar e responder.</p></div>}</CardContent></Card></div></div>;
}
