import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { BookOpen, Check, Loader2, Plus, Save, X } from "lucide-react";
import type { Tables } from "@/integrations/supabase/types";

type Livro = Tables<"livros">;
type Trilha = Tables<"trilhas">;
export const Route = createFileRoute("/_admin/admin/livros")({ component: AdminLivrosPage });
const LIVROS_HOME = [[1,"Mantenha Seu Amor Aceso",""],[2,"Cultura da Honra",""],[3,"Livro 3",""],[4,"Livro 4",""],[5,"Organize a Sua Desordem Mental",""],[6,"O Despertar da Leoa",""],[7,"Livro 7",""],[8,"Os Caminhos Sobrenaturais da Realeza",""],[9,"O Poder Sobrenatural de uma Mente Transformada",""],[10,"Impunível","Danny Silk"]] as const;
const novoForm={titulo:"",autor:"",ordem:1,categoria:"Jornada",descricao:"",objetivo:"",publico_alvo:"",trilha_id:""};
function AdminLivrosPage(){
 const qc=useQueryClient(); const [selecionado,setSelecionado]=useState<string|null>(null); const [criando,setCriando]=useState(false); const [form,setForm]=useState(novoForm);
 const livrosQuery=useQuery({queryKey:["admin-livros"],queryFn:async()=>{const {data,error}=await supabase.from("livros").select("*").order("ordem");if(error)throw error;return(data??[]) as Livro[];}});
 const trilhasQuery=useQuery({queryKey:["admin-trilhas"],queryFn:async()=>{const {data,error}=await supabase.from("trilhas").select("*").order("nome");if(error)throw error;return(data??[]) as Trilha[];}});
 const livros=livrosQuery.data??[]; const trilhas=trilhasQuery.data??[]; const porOrdem=useMemo(()=>new Map(livros.map(l=>[Number(l.ordem),l])),[livros]);
 const salvar=useMutation({mutationFn:async()=>{if(!form.titulo.trim())throw new Error("Informe o nome do livro ou curso.");if(!form.trilha_id)throw new Error("Selecione uma trilha.");const payload={titulo:form.titulo.trim(),autor:form.autor||null,ordem:Number(form.ordem)||1,categoria:form.categoria||null,descricao:form.descricao||null,objetivo:form.objetivo||null,publico_alvo:form.publico_alvo||null,trilha_id:form.trilha_id};const r=selecionado?await supabase.from("livros").update(payload).eq("id",selecionado):await supabase.from("livros").insert(payload);if(r.error)throw r.error;},onSuccess:async()=>{toast.success(selecionado?"Livro atualizado!":"Livro cadastrado!");fechar();await qc.invalidateQueries({queryKey:["admin-livros"]});},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Erro ao cadastrar livro.")});
 const cadastrarHome=useMutation({mutationFn:async(base:typeof LIVROS_HOME[number])=>{if(porOrdem.has(base[0]))return;const trilha=trilhas.find(t=>t.nome?.toLowerCase()==="jornada")??trilhas[0];if(!trilha)throw new Error("Nenhuma trilha cadastrada.");const {error}=await supabase.from("livros").insert({titulo:base[1],autor:base[2]||null,ordem:base[0],categoria:"Jornada",trilha_id:trilha.id});if(error)throw error;},onSuccess:async()=>{toast.success("Livro da Home cadastrado!");await qc.invalidateQueries({queryKey:["admin-livros"]});},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Erro ao cadastrar livro.")});
 function editar(l:Livro){setCriando(false);setSelecionado(l.id);setForm({titulo:l.titulo??"",autor:l.autor??"",ordem:Number(l.ordem??1),categoria:l.categoria??"Jornada",descricao:l.descricao??"",objetivo:l.objetivo??"",publico_alvo:l.publico_alvo??"",trilha_id:l.trilha_id});}
 function novoLivro(){const t=trilhas.find(x=>x.nome?.toLowerCase()==="jornada")??trilhas[0];setSelecionado(null);setCriando(true);setForm({...novoForm,ordem:livros.length+1,trilha_id:t?.id??""});}
 function fechar(){setSelecionado(null);setCriando(false);setForm(novoForm);}
 return <div className="w-full min-w-0 space-y-5 overflow-x-hidden"><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Cadastro</p><h1 className="break-words font-serif text-2xl font-semibold sm:text-3xl">Livros e cursos</h1><p className="mt-1 max-w-2xl text-sm leading-relaxed text-muted-foreground">Cadastre os mesmos livros exibidos na Home e mantenha tudo em um único cadastro.</p></div><Button className="w-full shrink-0 sm:w-auto" onClick={novoLivro}><Plus className="mr-2 h-4 w-4"/>Novo livro / curso</Button></div>
 <Card><CardHeader><CardTitle className="text-lg">Livros da Home</CardTitle><p className="text-sm text-muted-foreground">Os livros abaixo podem ser cadastrados diretamente no banco.</p></CardHeader><CardContent className="grid min-w-0 gap-2 sm:grid-cols-2">{LIVROS_HOME.map(([ordem,titulo,autor])=>{const livro=porOrdem.get(ordem);return <div key={ordem} className="flex min-w-0 items-center gap-2 rounded-lg border p-2.5 sm:gap-3 sm:p-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{ordem}</div><div className="min-w-0 flex-1"><p className="break-words text-sm font-medium">{livro?.titulo??titulo}</p>{(livro?.autor||autor)&&<p className="break-words text-xs text-muted-foreground">{livro?.autor||autor}</p>}</div>{livro?<Badge variant="secondary" className="shrink-0 text-[10px]"><Check className="mr-1 h-3 w-3"/>Cadastrado</Badge>:<Button size="sm" className="shrink-0" disabled={cadastrarHome.isPending||trilhasQuery.isLoading} onClick={()=>cadastrarHome.mutate([ordem,titulo,autor])}>Cadastrar</Button>}</div>})}</CardContent></Card>
 <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(260px,340px)_minmax(0,1fr)]"><Card className="min-w-0"><CardHeader><CardTitle className="text-lg">Livros cadastrados ({livros.length})</CardTitle></CardHeader><CardContent className="space-y-2">{livrosQuery.isLoading&&<p className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Carregando...</p>}{livrosQuery.isError&&<p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">Erro ao carregar os livros.</p>}{livros.map(l=><button key={l.id} type="button" onClick={()=>editar(l)} className={`flex w-full min-w-0 items-center gap-2 rounded-lg border p-3 text-left ${selecionado===l.id?"border-primary bg-primary/10":"hover:bg-secondary/60"}`}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold">{l.ordem}</div><span className="min-w-0 flex-1 break-words text-sm font-medium">{l.titulo}</span><span className="shrink-0 text-xs text-muted-foreground">Editar</span></button>)}</CardContent></Card>
 <Card className="min-w-0"><CardHeader><CardTitle className="text-lg">{selecionado?"Editar livro / curso":criando?"Cadastrar livro / curso":"Selecione um livro"}</CardTitle></CardHeader><CardContent>{!selecionado&&!criando?<div className="flex min-h-56 flex-col items-center justify-center px-2 text-center text-muted-foreground"><BookOpen className="mb-3 h-10 w-10 opacity-40"/><p>Escolha um livro da lista ou use “Novo livro / curso”.</p></div>:<form className="space-y-4" onSubmit={e=>{e.preventDefault();salvar.mutate();}}><div className="grid min-w-0 gap-4 sm:grid-cols-2"><Field label="Nome do livro / curso" className="sm:col-span-2"><Input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></Field><Field label="Autor"><Input value={form.autor} onChange={e=>setForm({...form,autor:e.target.value})}/></Field><Field label="Ordem"><Input type="number" value={form.ordem} onChange={e=>setForm({...form,ordem:Number(e.target.value)})}/></Field><Field label="Categoria"><Input value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}/></Field><Field label="Trilha"><Select value={form.trilha_id} onValueChange={v=>setForm({...form,trilha_id:v})}><SelectTrigger><SelectValue placeholder="Selecione a trilha"/></SelectTrigger><SelectContent>{trilhas.map(t=><SelectItem key={t.id} value={t.id}>{t.nome}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Descrição"><Textarea rows={4} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></Field><Field label="Objetivo"><Textarea rows={3} value={form.objetivo} onChange={e=>setForm({...form,objetivo:e.target.value})}/></Field><Field label="Público-alvo"><Textarea rows={3} value={form.publico_alvo} onChange={e=>setForm({...form,publico_alvo:e.target.value})}/></Field><div className="flex flex-col gap-2 sm:flex-row"><Button type="submit" disabled={salvar.isPending||trilhasQuery.isLoading} className="w-full sm:w-auto"><Save className="mr-2 h-4 w-4"/>{salvar.isPending?"Salvando...":"Salvar"}</Button><Button type="button" variant="outline" onClick={fechar} className="w-full sm:w-auto"><X className="mr-2 h-4 w-4"/>Cancelar</Button></div></form>}</CardContent></Card></div></div>;
}
function Field({label,children,className=""}:{label:string;children:React.ReactNode;className?:string}){return <div className={`min-w-0 space-y-1.5 ${className}`}><Label>{label}</Label>{children}</div>}
