import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Trash2, Upload, Loader2, FileText } from "lucide-react";
import { toast } from "sonner";

export const Route=createFileRoute("/_admin/admin/materiais")({component:AdminMateriaisPage});
const MAX=5*1024*1024;
type Livro={id:string;titulo:string}; type Material={id:string;livro_id:string;modulo:number;titulo:string;descricao:string|null;arquivo_nome:string|null;tamanho_bytes:number|null;mime_type:string|null;url:string};
function AdminMateriaisPage(){
 const qc=useQueryClient(); const [livroId,setLivroId]=useState(""); const [modulo,setModulo]=useState("1"); const [titulo,setTitulo]=useState(""); const [file,setFile]=useState<File|null>(null);
 const livrosQ=useQuery({queryKey:["admin-materiais-livros"],queryFn:async()=>{const {data,error}=await supabase.from("livros").select("id,titulo").order("ordem");if(error)throw error;return(data??[]) as Livro[]}});
 const matQ=useQuery({enabled:!!livroId,queryKey:["admin-materiais",livroId],queryFn:async()=>{const {data,error}=await supabase.from("materiais").select("id,livro_id,modulo,titulo,descricao,arquivo_nome,tamanho_bytes,mime_type,url").eq("livro_id",livroId).order("modulo").order("created_at");if(error)throw error;return(data??[]) as Material[]}});
 const enviar=useMutation({mutationFn:async()=>{if(!livroId)throw new Error("Selecione o livro/curso.");if(!file)throw new Error("Selecione um arquivo.");if(file.size>MAX)throw new Error("O arquivo deve ter no máximo 5 MB.");const ext=(file.name.split(".").pop()||"bin").toLowerCase();const path=`${livroId}/modulo-${Number(modulo)||1}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("book-materiais").upload(path,file,{upsert:false,contentType:file.type||"application/octet-stream"});if(up.error)throw up.error;const {error}=await supabase.from("materiais").insert({livro_id:livroId,modulo:Number(modulo)||1,titulo:titulo.trim()||file.name,arquivo_nome:file.name,tamanho_bytes:file.size,mime_type:file.type||"application/octet-stream",tipo:"arquivo",url:path});if(error){await supabase.storage.from("book-materiais").remove([path]);throw error}},onSuccess:()=>{toast.success("Material enviado para o módulo.");setTitulo("");setFile(null);const input=document.getElementById("material-file") as HTMLInputElement|null;if(input)input.value="";qc.invalidateQueries({queryKey:["admin-materiais",livroId]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Não foi possível enviar o material.")});
 const excluir=useMutation({mutationFn:async(m:Material)=>{const {error}=await supabase.from("materiais").delete().eq("id",m.id);if(error)throw error;if(m.url)await supabase.storage.from("book-materiais").remove([m.url])},onSuccess:()=>{toast.success("Material removido.");qc.invalidateQueries({queryKey:["admin-materiais",livroId]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Não foi possível remover.")});
 return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Conteúdo</p><h1 className="font-serif text-2xl font-semibold sm:text-3xl">Materiais dos módulos</h1><p className="mt-1 text-sm text-muted-foreground">Envie PDF ou qualquer outro tipo de arquivo, com limite de 5 MB, para cada módulo.</p></div><Card><CardHeader><CardTitle className="text-lg">Novo material</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5 sm:col-span-2"><Label>Livro / curso</Label><Select value={livroId} onValueChange={setLivroId}><SelectTrigger><SelectValue placeholder="Selecione o livro ou curso"/></SelectTrigger><SelectContent>{(livrosQ.data??[]).map(l=><SelectItem key={l.id} value={l.id}>{l.titulo}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Módulo</Label><Input type="number" min="1" value={modulo} onChange={e=>setModulo(e.target.value)}/></div><div className="space-y-1.5"><Label>Título do material</Label><Input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Ex.: Apostila do módulo 1"/></div><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="material-file">Arquivo — até 5 MB</Label><Input id="material-file" type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/>{file&&<p className="text-xs text-muted-foreground">{file.name} · {(file.size/1024/1024).toFixed(2)} MB</p>}</div><div className="sm:col-span-2"><Button disabled={enviar.isPending} onClick={()=>enviar.mutate()}>{enviar.isPending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Upload className="mr-2 h-4 w-4"/>}Enviar material</Button></div></CardContent></Card>{livroId&&<Card><CardHeader><CardTitle className="text-lg">Materiais cadastrados</CardTitle></CardHeader><CardContent className="space-y-2">{matQ.isLoading&&<p className="text-sm text-muted-foreground">Carregando…</p>}{!matQ.isLoading&&(matQ.data??[]).length===0&&<p className="text-sm text-muted-foreground">Nenhum material cadastrado.</p>}{(matQ.data??[]).map(m=><div key={m.id} className="flex items-center gap-3 rounded-lg border p-3"><FileText className="h-5 w-5 shrink-0 text-primary"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{m.titulo}</p><p className="text-xs text-muted-foreground">Módulo {m.modulo} · {m.arquivo_nome||"Arquivo"}{m.tamanho_bytes?` · ${(m.tamanho_bytes/1024/1024).toFixed(2)} MB`:""}</p></div><Badge variant="outline">Módulo {m.modulo}</Badge><Button size="icon" variant="ghost" aria-label="Remover material" onClick={()=>{if(confirm("Remover este material?"))excluir.mutate(m)}}><Trash2 className="h-4 w-4"/></Button></div>)}</CardContent></Card>}</div>;
}
