import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";
import { ChevronLeft, ChevronRight, Loader2, Plus, Save, Trash2 } from "lucide-react";

export const Route = createFileRoute("/_admin/admin/eventos")({ component: AdminEventosPage });
type Evento={id:string;titulo:string;descricao:string|null;data:string;hora:string|null;local:string|null;cidade:string|null;valor:number;vagas:number;livro_id:string|null;status:string};
type Livro={id:string;titulo:string;ordem:number};
const DIAS=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
const MESES=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
function AdminEventosPage(){
 const qc=useQueryClient(); const hoje=new Date(); const [mes,setMes]=useState(()=>new Date(hoje.getFullYear(),hoje.getMonth(),1)); const [editando,setEditando]=useState<Partial<Evento>|null>(null);
 const inicio=iso(new Date(mes.getFullYear(),mes.getMonth(),1)); const fim=iso(new Date(mes.getFullYear(),mes.getMonth()+1,0));
 const livrosQ=useQuery({queryKey:["admin-livros-min"],queryFn:async()=>{const {data,error}=await supabase.from("livros").select("id,titulo,ordem").order("ordem");if(error)throw error;return(data??[]) as Livro[]}});
 const eventosQ=useQuery({queryKey:["admin-eventos",inicio],queryFn:async()=>{const {data,error}=await supabase.from("eventos").select("id,titulo,descricao,data,hora,local,cidade,valor,vagas,livro_id,status").gte("data",inicio).lte("data",fim).order("data").order("hora");if(error)throw error;return(data??[]) as Evento[]}});
 const eventos=eventosQ.data??[]; const porDia=useMemo(()=>{const m:Record<string,Evento[]>={};for(const e of eventos)(m[e.data]??=[]).push(e);return m},[eventos]);
 const celulas=useMemo(()=>{const p=new Date(mes.getFullYear(),mes.getMonth(),1);const n=new Date(mes.getFullYear(),mes.getMonth()+1,0).getDate();return[...Array.from({length:p.getDay()},()=>null),...Array.from({length:n},(_,i)=>new Date(mes.getFullYear(),mes.getMonth(),i+1))]},[mes]);
 const salvar=useMutation({mutationFn:async(e:Partial<Evento>)=>{if(!e.titulo?.trim())throw new Error("Informe o título do encontro.");if(!e.data)throw new Error("Informe a data do encontro.");const payload={titulo:e.titulo.trim(),livro_id:e.livro_id||null,data:e.data,hora:e.hora||null,local:e.local||null,cidade:e.cidade||null,descricao:e.descricao||null,valor:Number(e.valor??0),vagas:Number(e.vagas??0)};const r=e.id?await supabase.from("eventos").update(payload).eq("id",e.id):await supabase.from("eventos").insert(payload);if(r.error)throw r.error},onSuccess:()=>{toast.success("Encontro salvo!");setEditando(null);qc.invalidateQueries({queryKey:["admin-eventos"]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Erro ao salvar encontro.")});
 const excluir=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("eventos").delete().eq("id",id);if(error)throw error},onSuccess:()=>{toast.success("Encontro removido.");setEditando(null);qc.invalidateQueries({queryKey:["admin-eventos"]})},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"Erro ao remover encontro.")});
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-2xl font-semibold">Calendário de encontros</h1><p className="text-sm text-muted-foreground">As programações cadastradas aparecem aqui. Clique em uma data para criar ou editar.</p></div><Button type="button" className="gap-2" onClick={()=>setEditando({data:iso(hoje),hora:"19:00",valor:0,vagas:0})}><Plus className="h-4 w-4"/>Novo encontro</Button></div>
 <Card><CardContent className="p-4"><div className="mb-3 flex items-center justify-between"><Button type="button" size="icon" variant="ghost" onClick={()=>setMes(new Date(mes.getFullYear(),mes.getMonth()-1,1))}><ChevronLeft className="h-4 w-4"/></Button><p className="font-serif text-lg font-semibold">{MESES[mes.getMonth()]} {mes.getFullYear()}</p><Button type="button" size="icon" variant="ghost" onClick={()=>setMes(new Date(mes.getFullYear(),mes.getMonth()+1,1))}><ChevronRight className="h-4 w-4"/></Button></div><div className="grid grid-cols-7 gap-1 text-center text-xs font-semibold uppercase text-muted-foreground">{DIAS.map(d=><div key={d} className="py-1">{d}</div>)}</div><div className="grid grid-cols-7 gap-1">{celulas.map((d,i)=>!d?<div key={`v${i}`} className="min-h-20"/>:<button key={iso(d)} type="button" onClick={()=>setEditando({data:iso(d),hora:"19:00",valor:0,vagas:0})} className="min-h-20 rounded-md border border-border p-1 text-left hover:bg-secondary"><span className="text-xs font-semibold text-muted-foreground">{d.getDate()}</span><div className="mt-1 space-y-1">{(porDia[iso(d)]??[]).map(e=><span key={e.id} onClick={ev=>{ev.stopPropagation();setEditando(e)}} className="block truncate rounded bg-primary px-1 py-0.5 text-[11px] text-primary-foreground">{e.hora?`${e.hora.slice(0,5)} `:""}{e.titulo}</span>)}</div></button>)}</div>{eventosQ.isLoading&&<p className="mt-3 text-sm text-muted-foreground"><Loader2 className="mr-1 inline h-4 w-4 animate-spin"/>Carregando programações…</p>}</CardContent></Card>
 <div className="space-y-2">{eventos.map(e=><Card key={e.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-serif font-semibold">{e.titulo}</p><p className="text-xs text-muted-foreground">{new Date(e.data+"T00:00:00").toLocaleDateString("pt-BR")} {e.hora?.slice(0,5)??""}{e.local?` · ${e.local}`:""}{e.cidade?` · ${e.cidade}`:""}</p></div><Button type="button" size="sm" variant="outline" onClick={()=>setEditando(e)}>Editar</Button></CardContent></Card>)}</div>
 <Dialog open={!!editando} onOpenChange={o=>!o&&setEditando(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{editando?.id?"Editar encontro":"Novo encontro"}</DialogTitle></DialogHeader>{editando&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();salvar.mutate(editando)}}><div className="space-y-1.5"><Label>Título</Label><Input value={editando.titulo??""} onChange={e=>setEditando(s=>({...s,titulo:e.target.value}))}/></div><div className="space-y-1.5"><Label>Livro / curso</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={editando.livro_id??""} onChange={e=>setEditando(s=>({...s,livro_id:e.target.value||null}))}><option value="">— sem livro / curso —</option>{(livrosQ.data??[]).map(l=><option key={l.id} value={l.id}>{l.ordem}. {l.titulo}</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Data</Label><Input type="date" value={editando.data??""} onChange={e=>setEditando(s=>({...s,data:e.target.value}))}/></div><div className="space-y-1.5"><Label>Horário</Label><Input type="time" value={(editando.hora??"").slice(0,5)} onChange={e=>setEditando(s=>({...s,hora:e.target.value}))}/></div><div className="space-y-1.5"><Label>Local</Label><Input value={editando.local??""} onChange={e=>setEditando(s=>({...s,local:e.target.value}))}/></div><div className="space-y-1.5"><Label>Cidade</Label><Input value={editando.cidade??""} onChange={e=>setEditando(s=>({...s,cidade:e.target.value}))}/></div><div className="space-y-1.5"><Label>Valor (R$)</Label><Input type="number" step="0.01" value={editando.valor??0} onChange={e=>setEditando(s=>({...s,valor:Number(e.target.value)}))}/></div><div className="space-y-1.5"><Label>Vagas</Label><Input type="number" value={editando.vagas??0} onChange={e=>setEditando(s=>({...s,vagas:Number(e.target.value)}))}/></div></div><div className="space-y-1.5"><Label>Descrição</Label><TextareaFallback value={editando.descricao??""} onChange={v=>setEditando(s=>({...s,descricao:v}))}/></div><div className="flex flex-wrap gap-2"><Button type="submit" disabled={salvar.isPending} className="gap-2">{salvar.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Salvar</Button>{editando.id&&<Button type="button" variant="ghost" onClick={()=>excluir.mutate(editando.id)}><Trash2 className="mr-1 h-4 w-4"/>Excluir</Button>}</div></form>}</DialogContent></Dialog></div>
}
function TextareaFallback({value,onChange}:{value:string;onChange:(v:string)=>void}){return <textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} className="flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm"/>}
