/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrilhasIdRouteImport } from './routes/trilhas.$id'
import { Route as LivrosIdRouteImport } from './routes/livros.$id'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedInscricaoEventoIdRouteImport } from './routes/_authenticated/inscricao.$eventoId'
import { Route as AuthenticatedAdminTrilhasRouteImport } from './routes/_authenticated/admin.trilhas'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminPresencasRouteImport } from './routes/_authenticated/admin.presencas'
import { Route as AuthenticatedAdminParticipantesRouteImport } from './routes/_authenticated/admin.participantes'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminLivrosRouteImport } from './routes/_authenticated/admin.livros'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminCertificadosRouteImport } from './routes/_authenticated/admin.certificados'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasIdRoute = TrilhasIdRouteImport.update({
  id: '/trilhas/$id',
  path: '/trilhas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosIdRoute = LivrosIdRouteImport.update({
  id: '/livros/$id',
  path: '/livros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedInscricaoEventoIdRoute =
  AuthenticatedInscricaoEventoIdRouteImport.update({
    id: '/inscricao/$eventoId',
    path: '/inscricao/$eventoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrilhasRoute =
  AuthenticatedAdminTrilhasRouteImport.update({
    id: '/trilhas',
    path: '/trilhas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPresencasRoute =
  AuthenticatedAdminPresencasRouteImport.update({
    id: '/presencas',
    path: '/presencas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParticipantesRoute =
  AuthenticatedAdminParticipantesRouteImport.update({
    id: '/participantes',
    path: '/participantes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLivrosRoute =
  AuthenticatedAdminLivrosRouteImport.update({
    id: '/livros',
    path: '/livros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCertificadosRoute =
  AuthenticatedAdminCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/livros/$id': typeof LivrosIdRoute
  '/trilhas/$id': typeof TrilhasIdRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/livros': typeof AuthenticatedAdminLivrosRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/participantes': typeof AuthenticatedAdminParticipantesRoute
  '/admin/presencas': typeof AuthenticatedAdminPresencasRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/inscricao/$eventoId': typeof AuthenticatedInscricaoEventoIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/livros/$id': typeof LivrosIdRoute
  '/trilhas/$id': typeof TrilhasIdRoute
  '/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/livros': typeof AuthenticatedAdminLivrosRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/participantes': typeof AuthenticatedAdminParticipantesRoute
  '/admin/presencas': typeof AuthenticatedAdminPresencasRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/inscricao/$eventoId': typeof AuthenticatedInscricaoEventoIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/livros/$id': typeof LivrosIdRoute
  '/trilhas/$id': typeof TrilhasIdRoute
  '/_authenticated/admin/certificados': typeof AuthenticatedAdminCertificadosRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/livros': typeof AuthenticatedAdminLivrosRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/participantes': typeof AuthenticatedAdminParticipantesRoute
  '/_authenticated/admin/presencas': typeof AuthenticatedAdminPresencasRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/trilhas': typeof AuthenticatedAdminTrilhasRoute
  '/_authenticated/inscricao/$eventoId': typeof AuthenticatedInscricaoEventoIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/certificados'
    | '/eventos'
    | '/inicio'
    | '/pagamentos'
    | '/perfil'
    | '/livros/$id'
    | '/trilhas/$id'
    | '/admin/certificados'
    | '/admin/eventos'
    | '/admin/livros'
    | '/admin/pagamentos'
    | '/admin/participantes'
    | '/admin/presencas'
    | '/admin/relatorios'
    | '/admin/trilhas'
    | '/inscricao/$eventoId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/certificados'
    | '/eventos'
    | '/inicio'
    | '/pagamentos'
    | '/perfil'
    | '/livros/$id'
    | '/trilhas/$id'
    | '/admin/certificados'
    | '/admin/eventos'
    | '/admin/livros'
    | '/admin/pagamentos'
    | '/admin/participantes'
    | '/admin/presencas'
    | '/admin/relatorios'
    | '/admin/trilhas'
    | '/inscricao/$eventoId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/certificados'
    | '/_authenticated/eventos'
    | '/_authenticated/inicio'
    | '/_authenticated/pagamentos'
    | '/_authenticated/perfil'
    | '/livros/$id'
    | '/trilhas/$id'
    | '/_authenticated/admin/certificados'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/livros'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/participantes'
    | '/_authenticated/admin/presencas'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/trilhas'
    | '/_authenticated/inscricao/$eventoId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LivrosIdRoute: typeof LivrosIdRoute
  TrilhasIdRoute: typeof TrilhasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$id': {
      id: '/trilhas/$id'
      path: '/trilhas/$id'
      fullPath: '/trilhas/$id'
      preLoaderRoute: typeof TrilhasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$id': {
      id: '/livros/$id'
      path: '/livros/$id'
      fullPath: '/livros/$id'
      preLoaderRoute: typeof LivrosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/inscricao/$eventoId': {
      id: '/_authenticated/inscricao/$eventoId'
      path: '/inscricao/$eventoId'
      fullPath: '/inscricao/$eventoId'
      preLoaderRoute: typeof AuthenticatedInscricaoEventoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/trilhas': {
      id: '/_authenticated/admin/trilhas'
      path: '/trilhas'
      fullPath: '/admin/trilhas'
      preLoaderRoute: typeof AuthenticatedAdminTrilhasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/presencas': {
      id: '/_authenticated/admin/presencas'
      path: '/presencas'
      fullPath: '/admin/presencas'
      preLoaderRoute: typeof AuthenticatedAdminPresencasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/participantes': {
      id: '/_authenticated/admin/participantes'
      path: '/participantes'
      fullPath: '/admin/participantes'
      preLoaderRoute: typeof AuthenticatedAdminParticipantesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/livros': {
      id: '/_authenticated/admin/livros'
      path: '/livros'
      fullPath: '/admin/livros'
      preLoaderRoute: typeof AuthenticatedAdminLivrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/certificados': {
      id: '/_authenticated/admin/certificados'
      path: '/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AuthenticatedAdminCertificadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCertificadosRoute: typeof AuthenticatedAdminCertificadosRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminLivrosRoute: typeof AuthenticatedAdminLivrosRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminParticipantesRoute: typeof AuthenticatedAdminParticipantesRoute
  AuthenticatedAdminPresencasRoute: typeof AuthenticatedAdminPresencasRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminTrilhasRoute: typeof AuthenticatedAdminTrilhasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCertificadosRoute: AuthenticatedAdminCertificadosRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminLivrosRoute: AuthenticatedAdminLivrosRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminParticipantesRoute: AuthenticatedAdminParticipantesRoute,
  AuthenticatedAdminPresencasRoute: AuthenticatedAdminPresencasRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminTrilhasRoute: AuthenticatedAdminTrilhasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedInscricaoEventoIdRoute: typeof AuthenticatedInscricaoEventoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedInscricaoEventoIdRoute: AuthenticatedInscricaoEventoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LivrosIdRoute: LivrosIdRoute,
  TrilhasIdRoute: TrilhasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
