/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as CadastroTurmaIdRouteImport } from './routes/cadastro.$turmaId'
import { Route as LivrosIdRouteImport } from './routes/livros.$id'
import { Route as TrilhasIdRouteImport } from './routes/trilhas.$id'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminCertificadosRouteImport } from './routes/_admin/admin.certificados'
import { Route as AdminAdminContaRouteImport } from './routes/_admin/admin.conta'
import { Route as AdminAdminEventosRouteImport } from './routes/_admin/admin.eventos'
import { Route as AdminAdminLivrosRouteImport } from './routes/_admin/admin.livros'
import { Route as AdminAdminPagamentosRouteImport } from './routes/_admin/admin.pagamentos'
import { Route as AdminAdminParticipantesRouteImport } from './routes/_admin/admin.participantes'
import { Route as AdminAdminPresencasRouteImport } from './routes/_admin/admin.presencas'
import { Route as AdminAdminRelatoriosRouteImport } from './routes/_admin/admin.relatorios'
import { Route as AdminAdminTurmasRouteImport } from './routes/_admin/admin.turmas'
import { Route as AuthenticatedInscricaoEventoIdRouteImport } from './routes/_authenticated/inscricao.$eventoId'
import { Route as AuthenticatedMatriculaInscricaoIdRouteImport } from './routes/_authenticated/matricula.$inscricaoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CadastroTurmaIdRoute = CadastroTurmaIdRouteImport.update({
  id: '/cadastro/$turmaId',
  path: '/cadastro/$turmaId',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosIdRoute = LivrosIdRouteImport.update({
  id: '/livros/$id',
  path: '/livros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasIdRoute = TrilhasIdRouteImport.update({
  id: '/trilhas/$id',
  path: '/trilhas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCertificadosRoute = AdminAdminCertificadosRouteImport.update({
  id: '/admin/certificados',
  path: '/admin/certificados',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminContaRoute = AdminAdminContaRouteImport.update({
  id: '/admin/conta',
  path: '/admin/conta',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminEventosRoute = AdminAdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLivrosRoute = AdminAdminLivrosRouteImport.update({
  id: '/admin/livros',
  path: '/admin/livros',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPagamentosRoute = AdminAdminPagamentosRouteImport.update({
  id: '/admin/pagamentos',
  path: '/admin/pagamentos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminParticipantesRoute = AdminAdminParticipantesRouteImport.update({
  id: '/admin/participantes',
  path: '/admin/participantes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPresencasRoute = AdminAdminPresencasRouteImport.update({
  id: '/admin/presencas',
  path: '/admin/presencas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminRelatoriosRoute = AdminAdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminTurmasRoute = AdminAdminTurmasRouteImport.update({
  id: '/admin/turmas',
  path: '/admin/turmas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedInscricaoEventoIdRoute =
  AuthenticatedInscricaoEventoIdRouteImport.update({
    id: '/inscricao/$eventoId',
    path: '/inscricao/$eventoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatriculaInscricaoIdRoute =
  AuthenticatedMatriculaInscricaoIdRouteImport.update({
    id: '/matricula/$inscricaoId',
    path: '/matricula/$inscricaoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/cadastro/$turmaId': typeof CadastroTurmaIdRoute
  '/livros/$id': typeof LivrosIdRoute
  '/trilhas/$id': typeof TrilhasIdRoute
  '/admin/certificados': typeof AdminAdminCertificadosRoute
  '/admin/conta': typeof AdminAdminContaRoute
  '/admin/eventos': typeof AdminAdminEventosRoute
  '/admin/livros': typeof AdminAdminLivrosRoute
  '/admin/pagamentos': typeof AdminAdminPagamentosRoute
  '/admin/participantes': typeof AdminAdminParticipantesRoute
  '/admin/presencas': typeof AdminAdminPresencasRoute
  '/admin/relatorios': typeof AdminAdminRelatoriosRoute
  '/admin/turmas': typeof AdminAdminTurmasRoute
  '/inscricao/$eventoId': typeof AuthenticatedInscricaoEventoIdRoute
  '/matricula/$inscricaoId': typeof AuthenticatedMatriculaInscricaoIdRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/cadastro/$turmaId': typeof CadastroTurmaIdRoute
  '/livros/$id': typeof LivrosIdRoute
  '/trilhas/$id': typeof TrilhasIdRoute
  '/admin/certificados': typeof AdminAdminCertificadosRoute
  '/admin/conta': typeof AdminAdminContaRoute
  '/admin/eventos': typeof AdminAdminEventosRoute
  '/admin/livros': typeof AdminAdminLivrosRoute
  '/admin/pagamentos': typeof AdminAdminPagamentosRoute
  '/admin/participantes': typeof AdminAdminParticipantesRoute
  '/admin/presencas': typeof AdminAdminPresencasRoute
  '/admin/relatorios': typeof AdminAdminRelatoriosRoute
  '/admin/turmas': typeof AdminAdminTurmasRoute
  '/inscricao/$eventoId': typeof AuthenticatedInscricaoEventoIdRoute
  '/matricula/$inscricaoId': typeof AuthenticatedMatriculaInscricaoIdRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/cadastro/$turmaId': typeof CadastroTurmaIdRoute
  '/livros/$id': typeof LivrosIdRoute
  '/trilhas/$id': typeof TrilhasIdRoute
  '/_admin/admin/certificados': typeof AdminAdminCertificadosRoute
  '/_admin/admin/conta': typeof AdminAdminContaRoute
  '/_admin/admin/eventos': typeof AdminAdminEventosRoute
  '/_admin/admin/livros': typeof AdminAdminLivrosRoute
  '/_admin/admin/pagamentos': typeof AdminAdminPagamentosRoute
  '/_admin/admin/participantes': typeof AdminAdminParticipantesRoute
  '/_admin/admin/presencas': typeof AdminAdminPresencasRoute
  '/_admin/admin/relatorios': typeof AdminAdminRelatoriosRoute
  '/_admin/admin/turmas': typeof AdminAdminTurmasRoute
  '/_authenticated/inscricao/$eventoId': typeof AuthenticatedInscricaoEventoIdRoute
  '/_authenticated/matricula/$inscricaoId': typeof AuthenticatedMatriculaInscricaoIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/calendario'
    | '/certificados'
    | '/eventos'
    | '/historico'
    | '/inicio'
    | '/pagamentos'
    | '/perfil'
    | '/cadastro/$turmaId'
    | '/livros/$id'
    | '/trilhas/$id'
    | '/admin/certificados'
    | '/admin/conta'
    | '/admin/eventos'
    | '/admin/livros'
    | '/admin/pagamentos'
    | '/admin/participantes'
    | '/admin/presencas'
    | '/admin/relatorios'
    | '/admin/turmas'
    | '/inscricao/$eventoId'
    | '/matricula/$inscricaoId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/calendario'
    | '/certificados'
    | '/eventos'
    | '/historico'
    | '/inicio'
    | '/pagamentos'
    | '/perfil'
    | '/cadastro/$turmaId'
    | '/livros/$id'
    | '/trilhas/$id'
    | '/admin/certificados'
    | '/admin/conta'
    | '/admin/eventos'
    | '/admin/livros'
    | '/admin/pagamentos'
    | '/admin/participantes'
    | '/admin/presencas'
    | '/admin/relatorios'
    | '/admin/turmas'
    | '/inscricao/$eventoId'
    | '/matricula/$inscricaoId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/calendario'
    | '/_authenticated/certificados'
    | '/_authenticated/eventos'
    | '/_authenticated/historico'
    | '/_authenticated/inicio'
    | '/_authenticated/pagamentos'
    | '/_authenticated/perfil'
    | '/cadastro/$turmaId'
    | '/livros/$id'
    | '/trilhas/$id'
    | '/_admin/admin/certificados'
    | '/_admin/admin/conta'
    | '/_admin/admin/eventos'
    | '/_admin/admin/livros'
    | '/_admin/admin/pagamentos'
    | '/_admin/admin/participantes'
    | '/_admin/admin/presencas'
    | '/_admin/admin/relatorios'
    | '/_admin/admin/turmas'
    | '/_authenticated/inscricao/$eventoId'
    | '/_authenticated/matricula/$inscricaoId'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CadastroTurmaIdRoute: typeof CadastroTurmaIdRoute
  LivrosIdRoute: typeof LivrosIdRoute
  TrilhasIdRoute: typeof TrilhasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cadastro/$turmaId': {
      id: '/cadastro/$turmaId'
      path: '/cadastro/$turmaId'
      fullPath: '/cadastro/$turmaId'
      preLoaderRoute: typeof CadastroTurmaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros/$id': {
      id: '/livros/$id'
      path: '/livros/$id'
      fullPath: '/livros/$id'
      preLoaderRoute: typeof LivrosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$id': {
      id: '/trilhas/$id'
      path: '/trilhas/$id'
      fullPath: '/trilhas/$id'
      preLoaderRoute: typeof TrilhasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/certificados': {
      id: '/_admin/admin/certificados'
      path: '/admin/certificados'
      fullPath: '/admin/certificados'
      preLoaderRoute: typeof AdminAdminCertificadosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/conta': {
      id: '/_admin/admin/conta'
      path: '/admin/conta'
      fullPath: '/admin/conta'
      preLoaderRoute: typeof AdminAdminContaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/eventos': {
      id: '/_admin/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminAdminEventosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/livros': {
      id: '/_admin/admin/livros'
      path: '/admin/livros'
      fullPath: '/admin/livros'
      preLoaderRoute: typeof AdminAdminLivrosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/pagamentos': {
      id: '/_admin/admin/pagamentos'
      path: '/admin/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminAdminPagamentosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/participantes': {
      id: '/_admin/admin/participantes'
      path: '/admin/participantes'
      fullPath: '/admin/participantes'
      preLoaderRoute: typeof AdminAdminParticipantesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/presencas': {
      id: '/_admin/admin/presencas'
      path: '/admin/presencas'
      fullPath: '/admin/presencas'
      preLoaderRoute: typeof AdminAdminPresencasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/relatorios': {
      id: '/_admin/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminAdminRelatoriosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/turmas': {
      id: '/_admin/admin/turmas'
      path: '/admin/turmas'
      fullPath: '/admin/turmas'
      preLoaderRoute: typeof AdminAdminTurmasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/inscricao/$eventoId': {
      id: '/_authenticated/inscricao/$eventoId'
      path: '/inscricao/$eventoId'
      fullPath: '/inscricao/$eventoId'
      preLoaderRoute: typeof AuthenticatedInscricaoEventoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matricula/$inscricaoId': {
      id: '/_authenticated/matricula/$inscricaoId'
      path: '/matricula/$inscricaoId'
      fullPath: '/matricula/$inscricaoId'
      preLoaderRoute: typeof AuthenticatedMatriculaInscricaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminCertificadosRoute: typeof AdminAdminCertificadosRoute
  AdminAdminContaRoute: typeof AdminAdminContaRoute
  AdminAdminEventosRoute: typeof AdminAdminEventosRoute
  AdminAdminLivrosRoute: typeof AdminAdminLivrosRoute
  AdminAdminPagamentosRoute: typeof AdminAdminPagamentosRoute
  AdminAdminParticipantesRoute: typeof AdminAdminParticipantesRoute
  AdminAdminPresencasRoute: typeof AdminAdminPresencasRoute
  AdminAdminRelatoriosRoute: typeof AdminAdminRelatoriosRoute
  AdminAdminTurmasRoute: typeof AdminAdminTurmasRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminCertificadosRoute: AdminAdminCertificadosRoute,
  AdminAdminContaRoute: AdminAdminContaRoute,
  AdminAdminEventosRoute: AdminAdminEventosRoute,
  AdminAdminLivrosRoute: AdminAdminLivrosRoute,
  AdminAdminPagamentosRoute: AdminAdminPagamentosRoute,
  AdminAdminParticipantesRoute: AdminAdminParticipantesRoute,
  AdminAdminPresencasRoute: AdminAdminPresencasRoute,
  AdminAdminRelatoriosRoute: AdminAdminRelatoriosRoute,
  AdminAdminTurmasRoute: AdminAdminTurmasRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedInscricaoEventoIdRoute: typeof AuthenticatedInscricaoEventoIdRoute
  AuthenticatedMatriculaInscricaoIdRoute: typeof AuthenticatedMatriculaInscricaoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedInscricaoEventoIdRoute: AuthenticatedInscricaoEventoIdRoute,
  AuthenticatedMatriculaInscricaoIdRoute:
    AuthenticatedMatriculaInscricaoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CadastroTurmaIdRoute: CadastroTurmaIdRoute,
  LivrosIdRoute: LivrosIdRoute,
  TrilhasIdRoute: TrilhasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
