// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { initializeApp, cert, getApps } from 'firebase-admin/app'
import { getAuth } from 'firebase-admin/auth'

// Initialize Firebase Admin SDK
function getFirebaseAdmin() {
  if (getApps().length > 0) {
    return getApps()[0];
  }

  const FIREBASE_PROJECT_ID = process.env.VITE_FIREBASE_PROJECT_ID;
  const FIREBASE_PRIVATE_KEY = process.env.FIREBASE_PRIVATE_KEY;
  const FIREBASE_CLIENT_EMAIL = process.env.FIREBASE_CLIENT_EMAIL;

  if (!FIREBASE_PROJECT_ID || !FIREBASE_PRIVATE_KEY || !FIREBASE_CLIENT_EMAIL) {
    const missing = [
      !FIREBASE_PROJECT_ID && 'VITE_FIREBASE_PROJECT_ID',
      !FIREBASE_PRIVATE_KEY && 'FIREBASE_PRIVATE_KEY',
      !FIREBASE_CLIENT_EMAIL && 'FIREBASE_CLIENT_EMAIL',
    ].filter(Boolean);
    const message = `Missing Firebase environment variable(s): ${missing.join(', ')}. Set up Firebase Admin credentials.`;
    console.error(`[Firebase] ${message}`);
    throw new Error(message);
  }

  return initializeApp({
    credential: cert({
      projectId: FIREBASE_PROJECT_ID,
      privateKey: FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n'),
      clientEmail: FIREBASE_CLIENT_EMAIL,
    }),
  });
}

export const requireFirebaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const request = getRequest();
    
    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    try {
      const app = getFirebaseAdmin();
      const auth = getAuth(app);
      const decodedToken = await auth.verifyIdToken(token);

      if (!decodedToken.uid) {
        throw new Error('Unauthorized: No user ID found in token');
      }

      return next({
        context: {
          auth,
          userId: decodedToken.uid,
          claims: decodedToken,
        },
      });
    } catch (error) {
      console.error('[Firebase Auth] Token verification failed:', error);
      throw new Error('Unauthorized: Invalid token');
    }
  },
);
